# Generated by Django 3.1.3 on 2020-11-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
