# Generated by Django 3.1.3 on 2021-03-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_auto_20210313_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
