# Generated by Django 3.1.3 on 2021-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_auto_20210313_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='solution',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
